name: Sigma CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rizz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          standalone: true

      - name: Install Dependencies
        run: pnpm install

      - name: Prettier my beloved
        run: pnpm format

      - name: Please dont fail
        run: pnpm lint
